### ISSUE TITLE
details to make testbench work

### ISSUE THREAD

**Issue by jbaramidze** [TUK-FPGAHS2017/median.systemc#2]
Hello,

I implemented the module, and got the output image which looks more or less correct, but it's different from reference image, most likely because I made some assumptions regarding some details. they are:

1) how big is the kernel?
2) do we read-calculate-write or save calculated image in some buffer? that is, do we calculate median with updated neighbors?
3) what do we do with boundary pixels?

can you please tell me which options were chosen when calculating reference image?

thanks.

**Comment by cdeschryver** [comment]
@johFeldmann : Can you please specify how you've created the image for #1? Thx!
Christian

**Comment by johFeldmann** [comment]
I used a 3x3 kernel. I buffered my filtered pixels in a separate Buffer. In the end I overwrite the original picture with my buffered pixels. So the border of the pixel remains untouched. It also has the same size (100x100).

**Comment by jbaramidze** [comment]
Got the same result. thanks!
